### PR TITLE
Add CircleCI continuous integration

### PR DESCRIPTION
**Pull request by dhimmel**
The goal of this PR is to have CircleCI automatically run the tests we're implementing in #4, #14, & #17.

### CODE REVIEW

**Comment by dhimmel** [comment]
@awm33 our builds are currently failing -- see https://circleci.com/gh/cognoma/cognoml. How do you suggest we proceed?

**Comment by dhimmel** [comment]
@jessept @vasudevanv -- you may also want to look at why our builds are failing. It may have something to do with our `setup.py`.

**Comment by jessept** [comment]
@dhimmel @awm33 @vasudevanv it looks like the circleCI is trying to install using python 2.7. I'm guessing this is the default python. From [circleCI site](https://circleci.com/gh/cognoma/cognoml/4) under setup.py:

python setup.py install
zip_safe flag not set; analyzing archive contents...
Installed /home/ubuntu/cognoml/.eggs/pytest_runner-2.9-__py2.7.egg__

**Comment by dhimmel** [comment]
So should we merge this PR to fix that?

**Comment by jessept** [comment]
@dhimmel Yes, I will squash merge this PR. I am going to merge and anticipate seeing another issue for our testing but I want to see if it actually occurs.

**Comment by dhimmel** [comment]
[Getting](https://circleci.com/gh/cognoma/cognoml/6):

```
ImportError: No module named 'numpy'
```

Related to https://github.com/scikit-learn/scikit-learn/issues/4164#issuecomment-243259447?

**Comment by jessept** [comment]
@dhimmel it looks like this is a longstanding issue with conflicting virtual environments.

I was able to replicate the issue on my local machine. I get the same missing numpy issue when I try to run ```python setup.py install```:

  File "/Users/jesseprestwood-taylor/miniconda3/lib/python3.5/site-packages/setuptools-20.3-py3.5.egg/setuptools/sandbox.py", line 46, in _execfile
  File "/var/folders/gp/xqdgpt850dv9j1hy396f2rz00000gn/T/easy_install-6vtv4hbz/scipy-0.17.1/setup.py", line 265, in <module>
  File "/var/folders/gp/xqdgpt850dv9j1hy396f2rz00000gn/T/easy_install-6vtv4hbz/scipy-0.17.1/setup.py", line 253, in setup_package
ImportError: No module named 'numpy'

However, when I activate my virtual environment, I am able to install with no problem:
source activate cognoma-machine-learning
discarding /Users/jesseprestwood-taylor/miniconda3/bin from PATH
prepending /Users/jesseprestwood-taylor/miniconda3/envs/cognoma-machine-learning/bin to PATH
(cognoma-machine-learning)Jesses-MacBook-Air:cognoml jesseprestwood-taylor$ python setup.py install
...
Using /Users/jesseprestwood-taylor/miniconda3/envs/cognoma-machine-learning/lib/python3.5/site-packages
Finished processing dependencies for cognoml==0.1.0
(cognoma-machine-learning)Jesses-MacBook-Air:cognoml jesseprestwood-taylor

**Comment by jessept** [comment]
@dhimmel yes it looks related to that. We may have to add numpy explicitly to the virtualenv setup.

**Comment by vasudevanv** [comment]
I have had to do this in the past with CircleCI. I used a requirements.txt file with all the dependencies in the virtualenv setup. You will need to add the following to the circle.yml file

dependencies:
   pre:
     - pip install -r requirements.txt

**Comment by dhimmel** [comment]
@vasudevanv, nice. Want to submit that pull request to add:

```yml
dependencies: 
  pre: 
    - "pip install --requirement requirements.txt"
```

**Comment by vasudevanv** [comment]
Sure. Will submit it shortly.

**Pull request merged**
